# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dOVbPc3BDgYdxjuHKAUvfn6VQ1hY8N9X
"""

# SECTION A

#1
def evendiv(x,y,z):
    return(sum(list([i for i in range(x, y+1) if i%z==0])))

print(evendiv(1,10,2))

#2
def check(s):
    x=eval(s)
    if x:
        return True
    else:
     return False 

print(check("2 < 7 < 15"))
print(check("30 > 45 > 21 > 9"))
print(check("4 < 7 < 8< 12 > 2"))

#3
print("Enter the String: ")
str = input()

print("Enter a character: ")
char = input()

newstr = ""
for i in range(len(str)):
    if str[i]=='a' or str[i]=='e' or str[i]=='i' or str[i]=='o' or str[i]=='u':
        newstr = newstr + char
    else:
        newstr = newstr + str[i]

print("\nOriginal String:", str)
print("New String:", newstr)

#4
def factorial(n):
      
    if n == 0:
        return 1
     
    return n * factorial(n-1)
  

num = 10;
print("Factorial of", num, "is",
factorial(num))

#5
def hammingDist(str1, str2):
    i = 0
    count = 0
 
    while(i < len(str1)):
        if(str1[i] != str2[i]):
            count += 1
        i += 1
    return count
 

str1 = "abcde"
str2 = "cdefg"
 

print(hammingDist(str1, str2))

# SECTION B

#1
l = [1,2,'a','b']

def filter_list(l):
    new_list = []
    for x in l:
        if type(x) == int:
            new_list.append(x)
    return new_list

print(filter_list(l))

#2
def string(str1):

    rstr1 = ''
    index = len(str1)
    while index > 0:
        rstr1 += str1[ index - 1 ]
        index = index - 1
    return rstr1
print(string('Vedant').swapcase())

#3
list=[1,6,8,9,5,4,"Ved","car","class",69]
first=list[0]
middle=list[1:-1]
last=list[-1]
print("first =",first ,"middle =",middle,"last = ",last)

#4
def recur_factorial(n):
   if n == 1:
       return n
   else:
       return n*recur_factorial(n-1)

num = int(input("Enter the number : "))


if num < 0:
   print("Sorry, factorial does not exist for negative numbers")
elif num == 0:
   print("The factorial of 0 is 1")
else:
   print("The factorial of", num, "is", recur_factorial(num))

#5
def move_to_end(lst,el):
    lst.append(lst.pop(lst.index(el)))
    return lst

print(move_to_end([1, 3, 2, 4, 4, 1], 1))
print(move_to_end([7, 8, 9, 1, 2, 3, 4], 9))
print(move_to_end(["a","a","a","b"], "a"))

# SECTION C

#1
def multichar(text, n):
    return ''.join([x * n for x in text])
multichar("Vedant",2)

#2
def reverse(arg):
	if isinstance(arg, bool):
		return not arg
	else:
		return('boolean expected')

def reverse(arg=None):
	return not arg if type(arg) == bool else "boolean expected"

print(reverse(True)) 
print(reverse(False)) 
print(reverse(0)) 
print(reverse(None))

#3
def fn(a):
    res = 0.5
    for i in range(a):
        res *= 2
    
    return res / 1000 
fn(1)

#5

listl=[i for i in range (4) if(i%2==0)]

print(listl)

# SECTION D

#1
l = [6,9,4,'ved','budukale']
output = [x for x in l if type(x) != str]
print(output)

#3
import math
pi = math.pi
def volume(r, h):
    return (1 / 3) * pi * r * r * h
def surfacearea(r, s):
    return pi * r * s + pi * r * r
radius = float(2)
height = float(3)
slat_height = float(5)
print( "Volume Of Cone : ", volume(radius, height) )
print( "Surface Area Of Cone : ", surfacearea(radius, slat_height) )

#5
def missing_num(lst):

   for n in range(1,11):

       if n not in lst:

           print(n)

lst = (1,3,4,5,6,7,8,9,10)

missing_num(lst)